### ISSUE TITLE
Feature Request: Specific Filters/Functions in the Workbook to pivot around Mobile Devices vs Computers

### ISSUE THREAD

**Issue by MrEMMDeeEMM** [thenikk/Oceanleaf#1]
Nice work so far! Thank you!
I would like to see OS Filters, specifically Computers vs Mobile Devices.
e.g. 
Computers > Windows*, macOS, Chrome OS, Linux
Mobile Devices > Android*, iOS/iPadOS
*Sub-categories are available such as Android (fully managed), Android (personally-owned work profile) etc.
Other > (OS may not be known)

Within the same context, it would be good to pivot on device serial number as it is usually the most unique identifier, tracking changes to primary user, phone number, iccid across the multiple "slots" (eSim card slots included) of the device.

An extremely useful data point to log is the "Activation Lock Bypass Code" for iOS/iPadOS.
For example when an iOS/iPadOS device is put into storage, if the Apple ID is signed in and Find My* is left enabled, there is a risk that the "Activation Lock Bypass Code" is lost during the device clean up rules processes which delete the Intune record due to the device not checking in keeping the record active.

**Comment by thenikk** [comment]
OS Filters -> unfortunately I don't see an option to filter for the OS in the Logs sent from Intune to LAW. Or have you found a way to do so?

Device serial number -> also here, I don't see this reflected in the logs

Activation Lock Bypass -> can you please give more insights to this? Is there a log type to query for this?
